### ISSUE TITLE
Your drop-down is broken on safari iOS

### ISSUE THREAD

**Issue by mismosmi** [steven-tey/precedent#2]
https://user-images.githubusercontent.com/26325283/212402167-2c3f2381-984b-466f-a524-ad8b934d8f44.MOV

**Comment by edgarasben** [comment]
Some weird positioning even in Chromium (Arc) too.
<img width="661" alt="image" src="https://user-images.githubusercontent.com/725324/212406454-279ec4bc-3dc6-4e22-b012-ac64b3d5aba5.png">

**Comment by steven-tey** [comment]
@mismosmi looking into that right now! Thanks for the heads-up! 

@edgarasben I can't repro this in Arc <picture data-single-emoji=":hmmm:" title=":hmmm:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..ZlLP0GUNfILyoSGP.j3dH6g13SntCTOjS4KsIeJQdA9ZQ9YZktRMIlDj_iFVrcGpL3cABmUKaDr9y40RTuYOSCoIEYqfL3qzQnMsPXr3F7L0pUud3htlq__WcVpOWl2-LWA.sn8bADbyVKyP2hb92L6pnA" alt=":hmmm:" align="absmiddle"></picture>

**Comment by edgarasben** [comment]
> @mismosmi looking into that right now! Thanks for the heads-up!
> 
> @edgarasben I can't repro this in Arc <img alt=":hmmm:" width="20" height="auto" src="https://camo.githubusercontent.com/e3b1c57507b37dceaa6a5440ecb1d61426e28596189c54bfd02686217a0a5c00/68747470733a2f2f73696e676c652d656d6f6a692e76657263656c2e6170702f6170692f656d6f6a692f65794a68624763694f694a6b615849694c434a6c626d4d694f694a424d6a553252304e4e496e302e2e5a6c4c503047554e66494c796f5347502e6a33644836673133536e7443544f6a53344b7349654a516441395a5139595a6b74524d496c446a5f694656726347704c336341426d554b61447239793430525475594f53436f49455971664c33717a516e4d735058723346374c30705575643368746c715f5f576356704f576c322d4c57412e736e386241446279564b795032686239324c36706e41">

It happens for me on the first hard-refresh only:

https://user-images.githubusercontent.com/725324/212412774-16fa1a60-b4f3-45c6-801d-d28bc2e53183.mov

**Comment by steven-tey** [comment]
@edgarasben Oooooh thanks for the info, I was able to repro! Will look into it!

**Comment by amanzrx4** [comment]
There's some overflow issue as well. Is the project accepting PRs? @steven-tey

**Comment by steven-tey** [comment]
Yes it is! @amanzrx4 – feel free to PR! :)

**Comment by steven-tey** [comment]
@mismosmi @edgarasben both the dropdown z index issue + the Arc issue should be fixed now!

Turns out it was a super obscure Framer Motion bug lol so I switched to Tailwind animate: https://github.com/steven-tey/precedent/blob/main/pages/index.tsx#L81

Thanks again for reporting this!

**Comment by edgarasben** [comment]
@steven-tey the bug is still there! If you reload the page and quickly click selector WHILE page is still animating in, you will get the same problem.
