### ISSUE TITLE
Two <main> elements in the markup

### ISSUE THREAD

**Issue by Aesop7** [steven-tey/precedent#21]
Hi, I noticed that there are two ```main``` elements in the markup.  https://validator.w3.org/nu/?doc=https%3A%2F%2Fprecedent.dev%2F  I'm sure it's not a big issue, but I'd hate for it to break a screen reader for someone.

**Comment by steven-tey** [comment]
oh great catch! do you wanna PR to fix this? AFAIK you can just change [this line](https://github.com/steven-tey/precedent/blob/main/pages/_app.tsx#L28) to `<div>` and it should work

**Comment by steven-tey** [comment]
Will be fixed by https://github.com/steven-tey/precedent/pull/22
