### ISSUE TITLE
A non-technical question

### ISSUE THREAD

**Issue by chhpt** [steven-tey/precedent#24]
Hello, may I know how you made the screen recording?

**Comment by AshikNesin** [comment]
@chhpt  I think, it is recorded using https://www.screen.studio (transitions looks similar).

**Comment by chhpt** [comment]
@AshikNesin Thanks for your answer

**Comment by steven-tey** [comment]
I actually used ScreenFlow for this: http://www.telestream.net/screenflow/overview.htm

Screen Studio is pretty awesome, I've used it in the past before! Screenflow does have better flexibility but it with a learning curve!
