### ISSUE TITLE
Change 100 lighthouse score circle to accurate representation

### ISSUE THREAD

**Issue by bdlowery** [steven-tey/precedent#26]
The template boasts 100 performance on lighthouse, but in reality the performance is around 60/100 if you use the real lighthouse - the one google will use to evaluate your website on the search engine results page. It even fails the core web vitals assessment.

https://pagespeed.web.dev/report?url=https%3A%2F%2Fprecedent.dev%2F

**Comment by steven-tey** [comment]
LGTM on Desktop:
![CleanShot 2023-03-13 at 22 48 28](https://user-images.githubusercontent.com/28986134/224888431-125074f0-1987-482e-be74-f6a07650f9fc.png)

Odd that Mobile is performing so poorly, will look into it. Closing this issue for now!

**Comment by bdlowery** [comment]
mobile is 75 👍
