### ISSUE TITLE
Cannot login on the website 

### ISSUE THREAD

**Issue by hansfpc** [steven-tey/precedent#31]
I don't know why but I am unable to authenticate

<img width="544" alt="image" src="https://user-images.githubusercontent.com/12705403/227524573-df969ac5-6623-4ecd-835d-bf2e72b7f68d.png">

What can I do? I would like to see the site in action 😞

**Comment by uqurtosun** [comment]
Hello hansfpc,

**Project needs PostgreSQL database, follow the steps below**
- https://dev.new just create PostgreSQL  databese
-  After click the menu "connect" copy DATABASE_URL
-  After open project prisma -> schema.prisma  3 line paste  url="DATABASE_URL"
-  After comman line "npx prisma migrate dev --name init" paste Enter.

**Your database is now set up.**

There will be a file called "env.example" in the project main directory, change the name of this file to "env.local"
Fill in the google information in the env.local file.

Restart the project after doing these steps. It will most likely work flawlessly.

**Comment by hansfpc** [comment]
thank you!
