### ISSUE TITLE
Tooltip z-indexes

### ISSUE THREAD

**Issue by mehulkar** [steven-tey/precedent#4]
Tooltips might need some love

<img width="481" alt="CleanShot 2023-01-13 at 15 17 22@2x" src="https://user-images.githubusercontent.com/490968/212436007-879d202a-6422-4781-918a-5b1049fc641d.png">

**Comment by steven-tey** [comment]
This has been fixed – thanks for the bug report Mehul!

Turns out it was a super obscure Framer Motion bug lol so I switched to Tailwind animate: https://github.com/steven-tey/precedent/blob/main/pages/index.tsx#L81
