### ISSUE TITLE
When i try to deploy it gives me this error ( Error occurred prerendering page)

### ISSUE THREAD

**Issue by Ultrasclash** [steven-tey/precedent#46]
Error occurred prerendering page "/sitemap.xml". Read more: https://nextjs.org/docs/messages/prerender-error
--
15:06:47.327 | Error:
15:06:47.327 | Invalid `prisma.user.findMany()` invocation:
15:06:47.327 |  
15:06:47.327 |  
15:06:47.327 | The table `public.User` does not exist in the current database.

**Comment by antcar0929** [comment]
You should push your prisma db

**Comment by Vent3st** [comment]
> You should push your prisma db

thanks, how would we push prisma db? locally?

**Comment by steven-tey** [comment]
run `npx prisma db push`

it should also be automatically ran when you do `next build`
