### ISSUE TITLE
<dialog> element for modals!

### ISSUE THREAD

**Issue by mehulkar** [steven-tey/precedent#5]
`<dialog>` element is widely available now! I would recommend using it for modals :)
https://github.com/steven-tey/precedent/blob/main/components/shared/modal.tsx

**Comment by kylemh** [comment]
https://www.oidaisdes.org/native-dialog-element.en/ not quite ready for the big time.

**Comment by steven-tey** [comment]
I remember trying to do this with https://github.com/steven-tey/dub but for some reason `<dialog>` + `framer-motion` was throwing some weird bugs...will take another stab!

**Comment by steven-tey** [comment]
Update: yup, changing `motion.div` to `motion.dialog` breaks the modal 😅 

<img width="1800" alt="CleanShot 2023-01-14 at 19 14 51@2x" src="https://user-images.githubusercontent.com/28986134/212504183-61a365ac-ca15-4599-bf1e-ca92ff0764c4.png">

Might fix it if I have time but probably not a top priority for now
