### ISSUE TITLE
Add GitHubProvider

### ISSUE THREAD

**Issue by kelvinyelyen** [steven-tey/precedent#64]
Consider adding GitHubProvider as an optional authentication method. This simply showcases available options. I'd be happy to handle the implementation for you.

**Comment by AbrahimZaman360** [comment]
it's easy man! read nextauth docs

**Comment by kelvinyelyen** [comment]
Wasn't familiar with NextAuth back then, wanted a practical way to explore it.

**Comment by kelvinyelyen** [comment]
Explore in [GitHub Provider](https://next-auth.js.org/providers/github) if needed.

**Comment by kelvinyelyen** [comment]
> 

Recently found [Kinde Auth](https://kinde.com/) as well, it's similar to Clerk actually, been using it a lot recently. You can add it to your alternatives.
