### ISSUE TITLE
Repo can't find next libraries

### ISSUE THREAD

**Issue by MincePie** [steven-tey/precedent#66]
When i clone this library and try to run it, each of the next libraries is underlined with an error message along the lines of:

Cannot find module 'next-auth/react' or its corresponding type declarations.ts(2307)

Is there something that needs to be updated in this repo?

**Comment by steven-tey** [comment]
Will add a line in the README!

**Comment by AbrahimZaman360** [comment]
> @steven-tey I cloned the latest and got this error upon npm install
> ![image](https://github.com/steven-tey/precedent/assets/97182597/8e31c447-0c58-40bf-99c7-def220f06b48)
> 

Change from Canary to 13.5.5 in Package.json
